server:
    port: 8081
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/javapro08
        username: postgres
        password: "1234"
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        properties:
            hibernate:
                format_sql: true
scheduler:
    enabled: true
interval: PT02S
intreval_in_cron: 0 0 0 * * *
